/**
 * Enhanced Note types with full contextual information
 * Each note is self-contained with all context needed to understand it in isolation
 */

/**
 * Source type categorization
 */
export type NoteSourceType = 
  | 'website'           // Information from a web page
  | 'document'          // Information from an uploaded document (PDF, etc.)
  | 'user_prompt'       // Information directly from user's message
  | 'agent_ai'          // Information generated/inferred by AI
  | 'research'          // Information from AI research (web search + analysis)
  | 'conversation';     // Information from back-and-forth conversation

/**
 * Note category
 */
export type NoteCategory = 
  | 'dates'
  | 'deadlines'
  | 'documents'
  | 'people'
  | 'places'
  | 'goals'
  | 'requirements'
  | 'other';

/**
 * Source information for a note
 */
export interface NoteSource {
  type: NoteSourceType;
  
  // URL if from a website
  url?: string;
  
  // Document name if from a document
  documentName?: string;
  
  // Original message/query that led to this note
  originatingMessage?: string;
  
  // AI model used if generated by AI
  aiModel?: string;
  
  // Timestamp when the source was accessed/created
  sourceTimestamp: Date;
  
  // Additional metadata
  metadata?: Record<string, any>;
}

/**
 * Hierarchical path for precise note location
 * Example: "case.jurisdiction.court.location.address"
 * Example: "case.parties.plaintiff.name"
 * Example: "case.events.hearings.motion_to_compel.title"
 * Example: "document.motion_to_compel.date_filed"
 * Example: "evidence.bank_statements.date"
 */
export interface NotePath {
  // Full hierarchical path (e.g., "case.parties.plaintiff.name")
  path: string;
  
  // Path segments as an array for easier traversal
  // Example: ["case", "parties", "plaintiff", "name"]
  segments: string[];
  
  // References to other notes by their paths
  // Example: evidence.bank_statements.belongs_to -> ["case.parties.plaintiff"]
  references?: string[];
}

/**
 * Contextual information (who, what, when, where)
 * @deprecated Use NotePath for more precise location tracking
 */
export interface NoteContext {
  // Who: People, organizations involved
  who?: string[];
  
  // What: The specific subject/topic
  what?: string;
  
  // When: Temporal context (in addition to the note's own timestamps)
  when?: string;
  
  // Where: Location, place, venue
  where?: string;
  
  // Additional context fields
  relatedTo?: string[];  // Related notes or topics
}

/**
 * Enhanced Note interface with full contextual information
 */
export interface Note {
  id: string;
  
  // Core content
  content: string;
  category: NoteCategory;
  
  // Timestamps
  createdAt: Date;
  updatedAt: Date;
  
  // Source information - where did this note come from?
  source: NoteSource;
  
  // Hierarchical path for precise location tracking
  path?: NotePath;
  
  // Legacy contextual information - kept for backward compatibility
  // @deprecated Use path for more precise location tracking
  context: NoteContext;
  
  // UI state flags
  isNew?: boolean;        // For highlighting newly added notes
  isPending?: boolean;    // Waiting for user approval
  
  // Optional tags for additional organization
  tags?: string[];
  
  // Confidence score (0-100) if auto-extracted
  confidence?: number;
}

/**
 * Stored note format (for serialization)
 */
export interface StoredNote {
  id: string;
  content: string;
  category: NoteCategory;
  createdAt: string;  // ISO string
  updatedAt: string;  // ISO string
  source: {
    type: NoteSourceType;
    url?: string;
    documentName?: string;
    originatingMessage?: string;
    aiModel?: string;
    sourceTimestamp: string;  // ISO string
    metadata?: Record<string, any>;
  };
  path?: {
    path: string;
    segments: string[];
    references?: string[];
  };
  context: {
    who?: string[];
    what?: string;
    when?: string;
    where?: string;
    relatedTo?: string[];
  };
  isNew?: boolean;
  isPending?: boolean;
  tags?: string[];
  confidence?: number;
}

/**
 * Helper to convert Note to StoredNote
 */
export function serializeNote(note: Note): StoredNote {
  return {
    ...note,
    createdAt: note.createdAt.toISOString(),
    updatedAt: note.updatedAt.toISOString(),
    source: {
      ...note.source,
      sourceTimestamp: note.source.sourceTimestamp.toISOString(),
    },
    path: note.path,
  };
}

/**
 * Helper to convert StoredNote to Note
 * Handles backward compatibility with old note format
 */
export function deserializeNote(stored: StoredNote | any): Note {
  // Handle old notes that don't have source and context
  const source: NoteSource = stored.source || {
    type: 'agent_ai' as NoteSourceType,
    sourceTimestamp: new Date(stored.createdAt || new Date()),
    aiModel: 'unknown',
  };
  
  const context: NoteContext = stored.context || {
    who: undefined,
    what: undefined,
    when: undefined,
    where: undefined,
    relatedTo: undefined,
  };
  
  return {
    id: stored.id,
    content: stored.content,
    category: stored.category as NoteCategory,
    createdAt: new Date(stored.createdAt),
    updatedAt: new Date(stored.updatedAt),
    source: {
      ...source,
      sourceTimestamp: new Date(source.sourceTimestamp),
    },
    path: stored.path,
    context,
    isNew: stored.isNew,
    isPending: stored.isPending,
    tags: stored.tags,
    confidence: stored.confidence,
  };
}

/**
 * Create a hierarchical path for a note
 * @param pathString Dot-separated path (e.g., "case.parties.plaintiff.name")
 * @param references Optional references to other note paths
 */
export function createNotePath(pathString: string, references?: string[]): NotePath {
  return {
    path: pathString,
    segments: pathString.split('.'),
    references,
  };
}
