/**
 * Enhanced Note types with full contextual information
 * Each note is self-contained with all context needed to understand it in isolation
 */

/**
 * Source type categorization
 */
export type NoteSourceType = 
  | 'website'           // Information from a web page
  | 'document'          // Information from an uploaded document (PDF, etc.)
  | 'user_prompt'       // Information directly from user's message
  | 'agent_ai'          // Information generated/inferred by AI
  | 'research'          // Information from AI research (web search + analysis)
  | 'conversation';     // Information from back-and-forth conversation

/**
 * Note category
 */
export type NoteCategory = 
  | 'dates'
  | 'deadlines'
  | 'documents'
  | 'people'
  | 'places'
  | 'goals'
  | 'requirements'
  | 'other';

/**
 * Source information for a note
 */
export interface NoteSource {
  type: NoteSourceType;
  
  // URL if from a website
  url?: string;
  
  // Document name if from a document
  documentName?: string;
  
  // Original message/query that led to this note
  originatingMessage?: string;
  
  // AI model used if generated by AI
  aiModel?: string;
  
  // Timestamp when the source was accessed/created
  sourceTimestamp: Date;
  
  // Additional metadata
  metadata?: Record<string, any>;
}

/**
 * Contextual information (who, what, when, where)
 */
export interface NoteContext {
  // Who: People, organizations involved
  who?: string[];
  
  // What: The specific subject/topic
  what?: string;
  
  // When: Temporal context (in addition to the note's own timestamps)
  when?: string;
  
  // Where: Location, place, venue
  where?: string;
  
  // Additional context fields
  relatedTo?: string[];  // Related notes or topics
}

/**
 * Enhanced Note interface with full contextual information
 */
export interface Note {
  id: string;
  
  // Core content
  content: string;
  category: NoteCategory;
  
  // Timestamps
  createdAt: Date;
  updatedAt: Date;
  
  // Source information - where did this note come from?
  source: NoteSource;
  
  // Contextual information - who/what/when/where
  context: NoteContext;
  
  // UI state flags
  isNew?: boolean;        // For highlighting newly added notes
  isPending?: boolean;    // Waiting for user approval
  
  // Optional tags for additional organization
  tags?: string[];
  
  // Confidence score (0-100) if auto-extracted
  confidence?: number;
}

/**
 * Stored note format (for serialization)
 */
export interface StoredNote {
  id: string;
  content: string;
  category: NoteCategory;
  createdAt: string;  // ISO string
  updatedAt: string;  // ISO string
  source: {
    type: NoteSourceType;
    url?: string;
    documentName?: string;
    originatingMessage?: string;
    aiModel?: string;
    sourceTimestamp: string;  // ISO string
    metadata?: Record<string, any>;
  };
  context: {
    who?: string[];
    what?: string;
    when?: string;
    where?: string;
    relatedTo?: string[];
  };
  isNew?: boolean;
  isPending?: boolean;
  tags?: string[];
  confidence?: number;
}

/**
 * Helper to convert Note to StoredNote
 */
export function serializeNote(note: Note): StoredNote {
  return {
    ...note,
    createdAt: note.createdAt.toISOString(),
    updatedAt: note.updatedAt.toISOString(),
    source: {
      ...note.source,
      sourceTimestamp: note.source.sourceTimestamp.toISOString(),
    },
  };
}

/**
 * Helper to convert StoredNote to Note
 */
export function deserializeNote(stored: StoredNote): Note {
  return {
    ...stored,
    createdAt: new Date(stored.createdAt),
    updatedAt: new Date(stored.updatedAt),
    source: {
      ...stored.source,
      sourceTimestamp: new Date(stored.source.sourceTimestamp),
    },
  };
}
