// Removed react-pdf CSS imports; not using react-pdf components and it can pull pdfjs unexpectedly
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
//tes
let jf=4
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
