// Removed react-pdf CSS imports; not using react-pdf components and it can pull pdfjs unexpectedly
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
//tes
// Ensure structuredClone exists in both server and client runtimes.
// Using @ungap/structured-clone for broad compatibility when Node/browser lacks it.
import structuredClonePolyfill from '@ungap/structured-clone';

// Lazily assign the polyfill only if missing to avoid overriding native impls.
if (typeof (globalThis as any).structuredClone !== 'function') {
  (globalThis as any).structuredClone = structuredClonePolyfill as typeof structuredClone;
}

// Removed react-pdf CSS imports; not using react-pdf components and it can pull pdfjs unexpectedly
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
let jf=4
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
